const ERRNO = {
    E2BIG        :   -7,
    EACCES       :  -13,
    EAGAIN       :  -11,
    EBADF        :   -9,
    EBUSY        :  -16,
    EDESTADDRREQ :  -89,
    EDQUOT       : -122,
    EEXIST       :  -17,
    EFAULT       :  -14,
    EFBIG        :  -27,
    EINTR        :   -4,
    EINVAL       :  -22,
    EIO          :   -5,
    EISDIR       :  -21,
    ELOOP        :  -40,
    EMFILE       :  -24,
    EMLINK       :  -31,
    ENAMETOOLONG :  -36,
    ENFILE       :  -23,
    ENODATA      :  -61,
    ENODEV       :  -19,
    ENOENT       :   -2,
    ENOMEM       :  -12,
    ENOSPC       :  -28,
    ENOSYS       :  -38,
    ENOTDIR      :  -20,
    ENOTEMPTY    :  -39,
    ENOTSUP      :  -95,
    ENXIO        :   -6,
    EOVERFLOW    :  -75,
    EPERM        :   -1,
    EPIPE        :  -32,
    ERANGE       :  -34,
    EROFS        :  -30,
    ETXTBSY      :  -26,
    EXDEV        :  -18
};

export { ERRNO }