#ifndef WF_JSONRPC_STATUS_H
#define WF_JSONRPC_STATUS_H

#define WF_JSONRPC_GOOD 0
#define WF_JSONRPC_BAD  -1
#define WF_JSONRPC_BAD_NOTIMPLEMENTED -2
#define WF_JSONRPC_BAD_TIMEOUT -3
#define WF_JSONRPC_BAD_BUSY -4
#define WF_JSONRPC_BAD_FORMAT -5

#endif
