name: 'build'

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Release
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install APT dependencies
        run: sudo apt install libfuse3-dev libwebsockets-dev libgtest-dev libgmock-dev ninja-build valgrind python3 python3-pip python3-setuptools python3-wheel

      - name: Install meson
        run: sudo pip3 install meson
      
      - name: Configure Meson
        run: meson .build

      - name: Build
        run: meson compile -C .build
  
      - name: Test
        run: meson test -C .build
