name: 'build'

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 17 * * 5'

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE: Release

    steps:
      - uses: actions/checkout@v4
      
      - name: Install APT dependencies
        run: sudo apt install libfuse3-dev libwebsockets-dev libgtest-dev libgmock-dev clang-tidy valgrind
      
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Unit Test
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target test

      - name: Memcheck
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target memcheck
